openapi: 3.0.3
info:
  title: 'The Affiliate Portal API'
  description: 'Start (and never finish) side projects with this API.'
  version: 1.0.0
servers:
  -
    url: '127.0.0.1:8000'
paths:
  /api/facturas/total:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: PaidStatus
          description: ''
          example: totam
          required: true
          schema:
            type: 'array(''Paid'', ''Undpaid'', ''Partially paid'')'
            description: ''
            example: totam
        -
          in: query
          name: SupplierNumber
          description: ''
          example: 4
          required: true
          schema:
            type: integer
            description: ''
            example: 4
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/invoiceLines:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: Developing
          description: ''
          example: qui
          required: true
          schema:
            type: 'null'
            description: ''
            example: qui
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/facturas/pagadas:
    post:
      summary: 'Store a newly created resource in storage.'
      description: ''
      parameters:
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/suppliernumber:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: id
          description: int
          example: quia
          required: true
          schema:
            type: 'user ID'
            description: int
            example: quia
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/consultaOTM/afiliado:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: Developing
          description: ''
          example: eos
          required: true
          schema:
            type: 'null'
            description: ''
            example: eos
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/proveedor:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: userId
          description: integer
          example: facere
          required: true
          schema:
            type: 'kinship id, to consult the provider to which it is associated'
            description: integer
            example: facere
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/auth/register:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: Photo
          description: ''
          example: null
          required: false
          schema:
            type: string
            format: binary
            description: ''
        -
          in: query
          name: name
          description: ''
          example: eveniet
          required: true
          schema:
            type: string
            description: ''
            example: eveniet
        -
          in: query
          name: email
          description: ''
          example: nobis
          required: true
          schema:
            type: string
            description: ''
            example: nobis
        -
          in: query
          name: identification
          description: ''
          example: 19
          required: true
          schema:
            type: integer
            description: ''
            example: 19
        -
          in: query
          name: telefono
          description: ''
          example: 18
          required: true
          schema:
            type: integer
            description: ''
            example: 18
        -
          in: query
          name: password
          description: ''
          example: inventore
          required: true
          schema:
            type: string
            description: ''
            example: inventore
        -
          in: query
          name: identificationPhoto
          description: ''
          example: null
          required: false
          schema:
            type: string
            format: binary
            description: ''
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/auth/login:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: email
          description: ''
          example: et
          required: true
          schema:
            type: string
            description: ''
            example: et
        -
          in: query
          name: password
          description: ''
          example: sequi
          required: true
          schema:
            type: password
            description: ''
            example: sequi
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/suppliers:
    post:
      summary: 'Show the form for creating a new resource.'
      description: ''
      parameters:
        -
          in: query
          name: identification
          description: ''
          example: 17
          required: true
          schema:
            type: integer
            description: ''
            example: 17
        -
          in: query
          name: FlagStatus
          description: string
          example: culpa
          required: true
          schema:
            type: 'It is to check if the invoice is valid or canceled [true, false]'
            description: string
            example: culpa
        -
          in: query
          name: PaidStatus
          description: string
          example: facere
          required: true
          schema:
            type: 'It is to check the paid status of the invoice. [Paid, Unpaid, Partially paid]'
            description: string
            example: facere
        -
          in: query
          name: InvoiceType
          description: string
          example: eum
          required: false
          schema:
            type: 'It is to consult the invoices by type of invoice.'
            description: string
            example: eum
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/user/updated:
    put:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: Photo
          description: ''
          example: null
          required: false
          schema:
            type: string
            format: binary
            description: ''
        -
          in: query
          name: name
          description: ''
          example: consequatur
          required: false
          schema:
            type: string
            description: ''
            example: consequatur
        -
          in: query
          name: email
          description: ''
          example: commodi
          required: false
          schema:
            type: string
            description: ''
            example: commodi
        -
          in: query
          name: identification
          description: ''
          example: 9
          required: false
          schema:
            type: integer
            description: ''
            example: 9
        -
          in: query
          name: telefono
          description: ''
          example: 8
          required: false
          schema:
            type: integer
            description: ''
            example: 8
        -
          in: query
          name: password
          description: ''
          example: rerum
          required: false
          schema:
            type: string
            description: ''
            example: rerum
        -
          in: query
          name: identificationPhoto
          description: ''
          example: null
          required: false
          schema:
            type: string
            format: binary
            description: ''
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/auth/logout:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
