openapi: 3.0.3
info:
  title: 'The Affiliate Portal API'
  description: 'Start (and never finish) side projects with this API.'
  version: 1.0.0
servers:
  -
    url: '127.0.0.1:8000'
paths:
  /api/healthcheck:
    get:
      summary: Healthcheck
      description: "Check that the service is up. If everything is okay, you'll get a 200 OK response.\n\nOtherwise, the request will fail with a 400 error, and a response listing the failed services."
      parameters:
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses:
        400:
          description: 'Service is unhealthy'
          content:
            application/json:
              schema:
                type: object
                example:
                  status: down
                  services:
                    database: up
                    redis: down
                properties:
                  status:
                    type: string
                    example: down
                    description: 'The status of this API (`up` or `down`).'
                  services:
                    type: object
                    example:
                      database: up
                      redis: down
                    description: 'Map of each downstream service and their status (`up` or `down`).'
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: up
                  services:
                    database: up
                    redis: up
                properties:
                  status:
                    type: string
                    example: up
                    description: 'The status of this API (`up` or `down`).'
                  services:
                    type: object
                    example:
                      database: up
                      redis: up
                    description: 'Map of each downstream service and their status (`up` or `down`).'
      tags:
        - ''
      security: []
  /api/facturas/total:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: PaidStatus
          description: ''
          example:
            - commodi
          required: true
          schema:
            type: array
            description: ''
            example:
              - commodi
            items:
              type: string
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - ''
      security: []
  /api/invoiceLines:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: Developing
          description: ''
          example: eum
          required: true
          schema:
            type: 'null'
            description: ''
            example: eum
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - ''
      security: []
  /api/facturas/pagadas:
    post:
      summary: 'Store a newly created resource in storage.'
      description: ''
      parameters:
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - ''
      security: []
  /api/suppliernumber:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: id_user
          description: ''
          example: 6
          required: true
          schema:
            type: integer
            description: ''
            example: 6
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - ''
      security: []
  /api/consultaOTM/afiliado:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: Developing
          description: ''
          example: id
          required: true
          schema:
            type: 'null'
            description: ''
            example: id
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - ''
      security: []
  /api/user:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses:
        302:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta http-equiv=\"refresh\" content=\"0;url='127.0.0.1:8000/127.0.0.1:8000/login'\" />\n\n        <title>Redirecting to 127.0.0.1:8000/127.0.0.1:8000/login</title>\n    </head>\n    <body>\n        Redirecting to <a href=\"127.0.0.1:8000/127.0.0.1:8000/login\">127.0.0.1:8000/127.0.0.1:8000/login</a>.\n    </body>\n</html>"
      tags:
        - ''
      security: []
  /api/auth/register:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: Photo
          description: ''
          example: null
          required: false
          schema:
            type: string
            format: binary
            description: ''
        -
          in: query
          name: name
          description: ''
          example: placeat
          required: true
          schema:
            type: string
            description: ''
            example: placeat
        -
          in: query
          name: email
          description: ''
          example: omnis
          required: true
          schema:
            type: string
            description: ''
            example: omnis
        -
          in: query
          name: identification
          description: ''
          example: 6
          required: true
          schema:
            type: integer
            description: ''
            example: 6
        -
          in: query
          name: telefono
          description: ''
          example: 10
          required: true
          schema:
            type: integer
            description: ''
            example: 10
        -
          in: query
          name: password
          description: ''
          example: provident
          required: true
          schema:
            type: string
            description: ''
            example: provident
        -
          in: query
          name: identificationPhoto
          description: ''
          example: null
          required: false
          schema:
            type: string
            format: binary
            description: ''
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - ''
      security: []
  /api/auth/login:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: email
          description: ''
          example: qui
          required: true
          schema:
            type: string
            description: ''
            example: qui
        -
          in: query
          name: password
          description: ''
          example: esse
          required: true
          schema:
            type: password
            description: ''
            example: esse
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - ''
      security: []
  /api/me:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses:
        302:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta http-equiv=\"refresh\" content=\"0;url='127.0.0.1:8000/127.0.0.1:8000/login'\" />\n\n        <title>Redirecting to 127.0.0.1:8000/127.0.0.1:8000/login</title>\n    </head>\n    <body>\n        Redirecting to <a href=\"127.0.0.1:8000/127.0.0.1:8000/login\">127.0.0.1:8000/127.0.0.1:8000/login</a>.\n    </body>\n</html>"
      tags:
        - ''
      security: []
  /api/suppliers:
    post:
      summary: 'Show the form for creating a new resource.'
      description: ''
      parameters:
        -
          in: query
          name: identification
          description: ''
          example: 2
          required: true
          schema:
            type: integer
            description: ''
            example: 2
        -
          in: query
          name: FlagStatus
          description: string
          example: animi
          required: true
          schema:
            type: 'It is to check if the invoice is valid or canceled [true, false]'
            description: string
            example: animi
        -
          in: query
          name: PaidStatus
          description: string
          example: consequatur
          required: true
          schema:
            type: 'It is to check the paid status of the invoice. [Paid, Unpaid, Partially paid]'
            description: string
            example: consequatur
        -
          in: query
          name: InvoiceType
          description: string
          example: maiores
          required: false
          schema:
            type: 'It is to consult the invoices by type of invoice.'
            description: string
            example: maiores
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - ''
      security: []
  '/api/user/updated/{id}':
    put:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: Photo
          description: ''
          example: null
          required: false
          schema:
            type: string
            format: binary
            description: ''
        -
          in: query
          name: name
          description: ''
          example: excepturi
          required: false
          schema:
            type: string
            description: ''
            example: excepturi
        -
          in: query
          name: email
          description: ''
          example: nisi
          required: false
          schema:
            type: string
            description: ''
            example: nisi
        -
          in: query
          name: identification
          description: ''
          example: 18
          required: false
          schema:
            type: integer
            description: ''
            example: 18
        -
          in: query
          name: telefono
          description: ''
          example: 8
          required: false
          schema:
            type: integer
            description: ''
            example: 8
        -
          in: query
          name: password
          description: ''
          example: nemo
          required: false
          schema:
            type: string
            description: ''
            example: nemo
        -
          in: query
          name: identificationPhoto
          description: ''
          example: null
          required: false
          schema:
            type: string
            format: binary
            description: ''
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - ''
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the updated.'
        example: ea
        required: true
        schema:
          type: string
  /api/auth/logout:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses: {  }
      tags:
        - ''
      security: []
tags:
  -
    name: ''
    description: ''
